repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/hadolint/hadolint
    rev: v2.8.0
    hooks:
      - id: hadolint-docker
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.1
    hooks:
      - id: shellcheck
  - repo: local
    hooks:
      - id: circleci
        name: CircleCI Config validate
        language: system
        entry: circleci config validate
        files: '\.circleci/config\.yml'
        stages:
          - commit
