apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: minecraft-bedrock

namespace: minecraft-bedrock

resources:
  - namespace.yaml
  - pvc.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
