---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock
spec:
  type: LoadBalancer
  ports:
  - name: minecraft
    port: 19132
    targetPort: minecraft
    protocol: UDP
  selector:
    app: minecraft-bedrock
